name: podinfo
namespace: podinfo
source:
  repoURL: https://stefanprodan.github.io/podinfo
  targetRevision: 6.6.3
  chart: podinfo

values:
  replicaCount: 3
  token: <path:secret/data/test_token#token>
