name: podinfo
namespace: podinfo
source:
  repoURL: https://stefanprodan.github.io/podinfo
  targetRevision: 6.6.3
  chart: podinfo

values_files:
  - values.yaml
  - values-prod.yaml

addons:
  path: extra
  vault: true
