apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    avp.kubernetes.io/path: "secret/data/test_token"
  labels:
    app.kubernetes.io/name: test
  name: test
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: podinfo
    helm:
      valuesObject:
        logLevel: <token>
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.6.3
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
