apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: test2
  name: test2
  namespace: argocd
spec:
  destination:
    namespace: test2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: test
    repoURL: https://github.com/imtpot/argocd-applications
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
